version: '2.1'
services:
  postgres:
    image: postgis/postgis:14-3.4-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    logging:
      options:
        max-size: 10m
        max-file: "3"
    ports:
      - '5432:5432'
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 6s
      timeout: 2s
      retries: 10

  script:
    build:
      dockerfile: Dockerfile
      context: .
    env_file:
      - ./.env
    depends_on:
      postgres:
        condition: service_healthy
#    ports:
#      - '9200:9200'

